import 'package:flutter/material.dart';

class AppLocalization {
  final Locale locale;
  AppLocalization(this.locale);

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'appName': 'Phone',
      'splashWelcome': 'Welcome to Phone Dialer',
      'splashDescription': 'A gorgeous, next-generation calling and contact management experience.',
      'privacyPolicy': 'Privacy Policy',
      'continueBtn': 'Continue',
      'selectLanguage': 'Select Language',
      'english': 'English',
      'hindi': 'Hindi (हिंदी)',
      'portuguese': 'Portuguese (Português)',
      'searchPlaceholder': 'Search name or number...',
      'noContacts': 'No contacts found',
      'noCallLogs': 'No call history',
      'recents': 'Recents',
      'contacts': 'Contacts',
      'favorites': 'Favorites',
      'settings': 'Settings',
      'yesterday': 'Yesterday',
      'today': 'Today',
      'older': 'Older Calls',
      'block': 'Block',
      'unblock': 'Unblock',
      'blocked': 'Blocked',
      'delete': 'Delete',
      'copy': 'Copy Number',
      'details': 'View Details',
      'edit': 'Edit Contact',
      'share': 'Share Contact',
      'addContact': 'Add Contact',
      'nameLabel': 'Full Name',
      'phoneLabel': 'Phone Number',
      'emailLabel': 'Email Address',
      'save': 'Save',
      'cancel': 'Cancel',
      'ok': 'OK',
      'addToFavorites': 'Add to Favorites',
      'removeFromFavorites': 'Remove from Favorites',
      'favSuccess': 'Favorite updated successfully!',
      'deleteConfirmTitle': 'Delete Contact',
      'deleteConfirmDesc': 'Are you sure you want to delete this contact?',
      'deleteLogConfirmDesc': 'Are you sure you want to delete this call log?',
      'numberCopied': 'Number copied to clipboard!',
      'whatsAppNotInstalled': 'WhatsApp Not Installed',
      'whatsAppInstallPlayStore': 'WhatsApp is not installed on this device. Redirect to the Play Store to install?',
      'whatsAppInstallBtn': 'Install',
      'whatsAppVideoCall': 'WhatsApp Video',
      'whatsAppVoiceCall': 'WhatsApp Voice',
      'whatsAppMessage': 'WhatsApp Message',
      'mute': 'Mute',
      'hold': 'Hold',
      'keypad': 'Keypad',
      'speaker': 'Speaker',
      'addCall': 'Add Call',
      'calling': 'Calling...',
      'ringing': 'Ringing...',
      'connected': 'Connected',
      'callOnHold': 'Call on Hold',
      'simSelectorTitle': 'Select Calling SIM',
      'sim1': 'SIM 1',
      'sim2': 'SIM 2',
      'themeLabel': 'Theme',
      'languageLabel': 'Language',
      'blockedListLabel': 'Blocked Contacts',
      'shareAppLabel': 'Share App',
      'rateAppLabel': 'Rate App',
      'version': 'Version 1.0.0',
      'rateTitle': 'Enjoying Callin?',
      'rateDesc': 'Please tap a star to give us feedback.',
      'rateThanks': 'Thank you for your rating!',
      'removedFromBlocklist': 'Contact unblocked successfully!',
      'addedToBlocklist': 'Contact added to blocklist!',
      'missedCall': 'Missed Call',
      'missedCallNotification': 'You missed a call from ',
    },
    'hi': {
      'appName': 'Phone',
      'splashWelcome': 'फ़ोन डायलर में आपका स्वागत है',
      'splashDescription': 'एक शानदार, अगली पीढ़ी का कॉलिंग और संपर्क प्रबंधन अनुभव।',
      'privacyPolicy': 'गोपनीयता नीति (Privacy Policy)',
      'continueBtn': 'जारी रखें',
      'selectLanguage': 'भाषा चुनें',
      'english': 'अंग्रेज़ी (English)',
      'hindi': 'हिंदी (Hindi)',
      'portuguese': 'पुर्तगाली (Portuguese)',
      'searchPlaceholder': 'नाम या नंबर खोजें...',
      'noContacts': 'कोई संपर्क नहीं मिला',
      'noCallLogs': 'कोई कॉल इतिहास नहीं',
      'recents': 'कॉल सूची',
      'contacts': 'संपर्क',
      'favorites': 'पसंदीदा',
      'settings': 'सेटिंग्स',
      'yesterday': 'कल (Yesterday)',
      'today': 'आज (Today)',
      'older': 'पुराने कॉल्स',
      'block': 'ब्लॉक करें',
      'unblock': 'अनब्लॉक करें',
      'blocked': 'ब्लॉक किया गया',
      'delete': 'हटाएं',
      'copy': 'नंबर कॉपी करें',
      'details': 'विवरण देखें',
      'edit': 'संपर्क बदलें',
      'share': 'संपर्क साझा करें',
      'addContact': 'नया संपर्क जोड़ें',
      'nameLabel': 'पूरा नाम',
      'phoneLabel': 'फ़ोन नंबर',
      'emailLabel': 'ईमेल पता',
      'save': 'सहेजें',
      'cancel': 'रद्द करें',
      'ok': 'ठीक है',
      'addToFavorites': 'पसंदीदा में जोड़ें',
      'removeFromFavorites': 'पसंदीदा से हटाएं',
      'favSuccess': 'पसंदीदा सफलता से अपडेट हुआ!',
      'deleteConfirmTitle': 'संपर्क हटाएं',
      'deleteConfirmDesc': 'क्या आप वाकई इस संपर्क को हटाना चाहते हैं?',
      'deleteLogConfirmDesc': 'क्या आप वाकई इस कॉल रिकॉर्ड को हटाना चाहते हैं?',
      'numberCopied': 'नंबर क्लिपबोर्ड पर कॉपी हो गया!',
      'whatsAppNotInstalled': 'व्हाट्सएप इंस्टॉल नहीं है',
      'whatsAppInstallPlayStore': 'इस डिवाइस में व्हाट्सएप इंस्टॉल नहीं है। इंस्टॉल करने के लिए प्ले स्टोर पर जाएं?',
      'whatsAppInstallBtn': 'इंस्टॉल करें',
      'whatsAppVideoCall': 'व्हाट्सएप वीडियो कॉल',
      'whatsAppVoiceCall': 'व्हाट्सएप वॉयस कॉल',
      'whatsAppMessage': 'व्हाट्सएप संदेश',
      'mute': 'म्यूट',
      'hold': 'होल्ड करें',
      'keypad': 'कीपैड',
      'speaker': 'स्पीकर',
      'addCall': 'कॉल जोड़ें',
      'calling': 'कॉल हो रही है...',
      'ringing': 'घंटी बज रही है...',
      'connected': 'जुड़ा हुआ',
      'callOnHold': 'कॉल होल्ड पर है',
      'simSelectorTitle': 'कॉलिंग सिम चुनें',
      'sim1': 'सिम १ (SIM 1)',
      'sim2': 'सिम २ (SIM 2)',
      'themeLabel': 'थीम (Theme)',
      'languageLabel': 'भाषा (Language)',
      'blockedListLabel': 'ब्लॉक की गई सूची',
      'shareAppLabel': 'ऐप शेयर करें',
      'rateAppLabel': 'ऐप को रेट करें',
      'version': 'संस्करण 1.0.0',
      'rateTitle': 'कॉलिन पसंद आया?',
      'rateDesc': 'कृपया हमें प्रतिक्रिया देने के लिए स्टार पर टैप करें।',
      'rateThanks': 'रेटिंग देने के लिए धन्यवाद!',
      'removedFromBlocklist': 'नंबर अनब्लॉक हो गया है!',
      'addedToBlocklist': 'नंबर ब्लॉक लिस्ट में जोड़ दिया गया है!',
      'missedCall': 'मिस कॉल',
      'missedCallNotification': 'आपके पास एक मिस कॉल है: ',
    },
    'pt': {
      'appName': 'Phone',
      'splashWelcome': 'Bem-vindo ao Discador',
      'splashDescription': 'Uma experiência de chamada e gerenciamento de contatos moderna e premium.',
      'privacyPolicy': 'Política de Privacidade',
      'continueBtn': 'Continuar',
      'selectLanguage': 'Selecione o Idioma',
      'english': 'Inglês',
      'hindi': 'Hindi',
      'portuguese': 'Português',
      'searchPlaceholder': 'Pesquisar nome ou número...',
      'noContacts': 'Nenhum contato encontrado',
      'noCallLogs': 'Sem histórico de chamadas',
      'recents': 'Recentes',
      'contacts': 'Contatos',
      'favorites': 'Favoritos',
      'settings': 'Ajustes',
      'yesterday': 'Ontem',
      'today': 'Hoje',
      'older': 'Mais antigas',
      'block': 'Bloquear',
      'unblock': 'Desbloquear',
      'blocked': 'Bloqueado',
      'delete': 'Excluir',
      'copy': 'Copiar Número',
      'details': 'Ver Detalhes',
      'edit': 'Editar Contato',
      'share': 'Compartilhar',
      'addContact': 'Adicionar Contato',
      'nameLabel': 'Nome Completo',
      'phoneLabel': 'Número de Telefone',
      'emailLabel': 'Endereço de E-mail',
      'save': 'Salvar',
      'cancel': 'Cancelar',
      'ok': 'OK',
      'addToFavorites': 'Adicionar aos Favoritos',
      'removeFromFavorites': 'Remover dos Favoritos',
      'favSuccess': 'Favorito atualizado com sucesso!',
      'deleteConfirmTitle': 'Excluir Contato',
      'deleteConfirmDesc': 'Tem certeza de que deseja excluir este contato?',
      'deleteLogConfirmDesc': 'Tem certeza de que deseja excluir este registro de chamada?',
      'numberCopied': 'Número copiado para a área de transferência!',
      'whatsAppNotInstalled': 'WhatsApp Não Instalado',
      'whatsAppInstallPlayStore': 'O WhatsApp não está instalado neste dispositivo. Redirecionar para a Play Store para instalar?',
      'whatsAppInstallBtn': 'Instalar',
      'whatsAppVideoCall': 'WhatsApp Vídeo',
      'whatsAppVoiceCall': 'WhatsApp Voz',
      'whatsAppMessage': 'WhatsApp Mensagem',
      'mute': 'Mudo',
      'hold': 'Aguardar',
      'keypad': 'Teclado',
      'speaker': 'Alto-falante',
      'addCall': 'Nova Chamada',
      'calling': 'Chamando...',
      'ringing': 'Chamando...',
      'connected': 'Conectado',
      'callOnHold': 'Chamada em Espera',
      'simSelectorTitle': 'Escolha o SIM Card',
      'sim1': 'SIM 1',
      'sim2': 'SIM 2',
      'themeLabel': 'Tema',
      'languageLabel': 'Idioma',
      'blockedListLabel': 'Contatos Bloqueados',
      'shareAppLabel': 'Compartilhar App',
      'rateAppLabel': 'Avaliar App',
      'version': 'Versão 1.0.0',
      'rateTitle': 'Gostou do Callin?',
      'rateDesc': 'Por favor, toque em uma estrela para nos dar seu feedback.',
      'rateThanks': 'Obrigado por nos avaliar!',
      'removedFromBlocklist': 'Contato desbloqueado com sucesso!',
      'addedToBlocklist': 'Contato bloqueado com sucesso!',
      'missedCall': 'Chamada Perdida',
      'missedCallNotification': 'Chamada perdida de ',
    }
  };

  String translate(String key) {
    String code = locale.languageCode;
    if (!_localizedValues.containsKey(code)) {
      code = 'en'; // default fallback
    }
    return _localizedValues[code]?[key] ?? key;
  }
}
